require_relative 'aggregator/count'
require_relative 'aggregator/sum'
require_relative 'aggregator/min'
require_relative 'aggregator/max'
require_relative 'aggregator/avg'
require_relative 'aggregator/variance'
require_relative 'aggregator/stddev'
require_relative 'aggregator/collect'
require_relative 'aggregator/concat'

require_relative 'operator/non_relational'
require_relative 'operator/relational'

require_relative 'reader/rash'
require_relative 'reader/alf_file'

require_relative 'renderer/rash'
require_relative 'renderer/text'
require_relative 'renderer/yaml'
require_relative 'renderer/json'
