require_relative 'aggregator/count'
require_relative 'aggregator/sum'
require_relative 'aggregator/min'
require_relative 'aggregator/max'
require_relative 'aggregator/avg'
require_relative 'aggregator/variance'
require_relative 'aggregator/stddev'
require_relative 'aggregator/collect'
require_relative 'aggregator/concat'

require_relative 'operator/non_relational'
require_relative 'operator/relational'
