{:supplier_id => 'S1', :part_id => 'P1', :quantity => 300}
{:supplier_id => 'S1', :part_id => 'P2', :quantity => 200}
{:supplier_id => 'S1', :part_id => 'P3', :quantity => 400}
{:supplier_id => 'S1', :part_id => 'P4', :quantity => 200}
{:supplier_id => 'S1', :part_id => 'P5', :quantity => 100}
{:supplier_id => 'S1', :part_id => 'P6', :quantity => 100}
{:supplier_id => 'S2', :part_id => 'P1', :quantity => 300}
{:supplier_id => 'S2', :part_id => 'P2', :quantity => 400}
{:supplier_id => 'S3', :part_id => 'P2', :quantity => 200}
{:supplier_id => 'S4', :part_id => 'P2', :quantity => 200}
{:supplier_id => 'S4', :part_id => 'P4', :quantity => 300}
{:supplier_id => 'S4', :part_id => 'P5', :quantity => 400}
